version: '2'

services:
  db:
    container_name: my_db
    build: ./db
    environment:
      - POSTGRES_DB=citygo_malaga
      - POSTGRES_USER=citygo
      - POSTGRES_PASSWORD=---------
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./temp-postgres-data/data:/var/lib/postgresql/data
  web:
    build: ./webapp/ShowcaseServer
    environment:
      - PYTHONUSERBASE=.webapp/ShowcaseServer/
    volumes:
      -  ./webapp:/webapp
    ports:
      - "8000:8000"
    container_name: my_web
    depends_on:
      - db
    command: python /webapp/ShowcaseServer/manage.py runserver 0.0.0.0:8000

volumes:
  db_data:
    external: true
